### PR TITLE
[JENKINS-41752] Fix PCT for 2.32.2

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-41752](https://issues.jenkins-ci.org/browse/JENKINS-41752)

- Force the creation of the user, to avoid depending on new User.ALLOW_USER_CREATION_VIA_URL property.
- Update test dependencies for instance to start.

@reviewbybees @stephenc

### CODE REVIEW

**Comment by armfergom** [comment]
🐝 as far as I understand it

**Comment by raul-arabaolaza** [comment]
Does [this comment](https://github.com/jenkinsci/credentials-binding-plugin/pull/31#discussion_r88903758) apply here as well? I mean, do we really need the subversion dependency  or can be avoided?

**Comment by varyvol** [comment]
@raul-arabaolaza it did. Anyway I think at the end is just a necessary dependency for the tests, but probably this way it's "cleaner". Changed.

**Comment by raul-arabaolaza** [comment]
I prefer this way, is coherent with [#PR-31](https://github.com/jenkinsci/credentials-binding-plugin/pull/31) and we do not add unneeded dependencies (the less subversion added the merrier :)) 

:bee:

**Pull request merged**
