### PR TITLE
[JENKINS-37541] Protect ourselves against deserialization with null binding

### PR DESCRIPTION
**Pull request by Vlatombe**
Also bumped version of parent POM

https://issues.jenkins-ci.org/browse/JENKINS-37541
@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Hmm. :bee:, though I would like to know why this is happening, as it indicates a bug elsewhere.

**Comment by Vlatombe** [comment]
Indeed, not sure what is the root cause (build record corruption maybe?). But in any case it never hurts to be defensive.

**Comment by mattstep** [comment]
🐝

**Comment by Vlatombe** [comment]
@reviewbybees done

**Pull request merged**
