### PR TITLE
[FIXED JENKINS-29255] Restricting secret file visibility to avoid "WARNING: UNPROTECTED PRIVATE KEY FILE!" when using as ssh key

### PR DESCRIPTION
**Pull request by Lohandus**
[JENKINS-29255](https://issues.jenkins-ci.org/browse/JENKINS-29255)

### CODE REVIEW

**Comment by jglick** [comment]
Somehow I missed this. At any rate, will need to merge with #3 when done.

**Comment by jglick** [comment]
Merge conflicts.

**Comment by jglick** [comment]
Do you plan to merge with `master` and resolve the conflicts here?

**Comment by Lohandus** [comment]
Rebased!

**Pull request merged**
